config/routes.rb
Rails.application.routes.draw do
  root 'goods#index'

  resources :goods, :only => [:new, :index, :create, :destroy]
end

app/models/good.rb
class Good < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  validates :name, :article, presence: true
  validates :name, :article, uniqueness: true

  before_validation do |good|
    good.article = good.article.upcase
  end

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :article, analyzer: 'english', index_options: 'offsets'
      indexes :name,    analyzer: 'russian', index_options: 'offsets'
    end
  end

  def self.search query
    if query 
      by_articles_search = where(article: query).to_a
      full_text_search   = __elasticsearch__.search({
        "query": {
          "bool": {
            "should": [
              { "match": { "article": query } },
              { "match": { "name": query } }
            ]
          }
        }
      }).records.to_a
      (by_articles_search + full_text_search).uniq
    else
      all.limit(10)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  def index
    @goods = Good.search params[:q]
  end

  def new
    @good = Good.new
  end

  def create
    @good = Good.new permited_params
    if @good.save
      redirect_to goods_path
    else
      render :new
    end
  end

  def destroy
    @good = Good.find params[:id]
    if @good.destroy
      redirect_to goods_path
    else
      redirect_to goods_path
    end
  end

  private
    def permited_params
      params.require(:good).permit(:article, :name)      
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
  def errors_for object
    if object.errors.any?
      content_tag(:div, class: "panel panel-danger") do
        concat(content_tag(:div, class: "panel-heading") do
          concat(content_tag(:h4, class: "panel-title") do
            concat "#{pluralize(object.errors.count, "error")} prohibited this #{object.class.name.downcase} from being saved:"
          end)
        end)
        concat(content_tag(:div, class: "panel-body") do
          concat(content_tag(:ul) do
            object.errors.full_messages.each do |msg|
              concat content_tag(:li, msg)
            end
          end)
        end)
      end
    end
  end
end

app/views/goods/_form.html.slim
= errors_for good

= form_for good do |f|
  .form-group
    = f.label :article
    = f.text_field :article, class: 'form-control'
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.submit 'Create', class: 'btn btn-primary'

app/views/goods/_good.html.slim
= "#{ good.article }: #{ good.name }"
'
= link_to 'delete', good_path(good), data: { method:'delete', confirm:'Are you shure?'}, class: 'text-danger'

app/views/goods/_search.html.slim
= form_tag '/goods', method:'GET', class: 'form-inline'
  .form-group
    = text_field_tag :q, params[:q], placeholder: 'search...', class: 'form-control'
  .form-group
    = submit_tag 'Search', class: 'btn btn-primary'

app/views/goods/index.html.slim
h2  Search
= render 'search'

h2 All goods
= link_to '+ new', new_good_path

- if @goods.any?
  ul#goods_list
    - @goods.each do |good|
      li 
        = render 'good', good: good

- else 
  p There is no goods for your query..
  p 
    ' But you can add new one
    = link_to 'here', new_good_path

app/views/goods/new.html.slim
h2  Add new one good

= render 'form', good: @good

= link_to 'Back to all goods', goods_path, class: 'btn btn-default'

app/views/layouts/application.html.slim
doctype 5
html
  head
    title ElasticsearchTestTask
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    .container
      = yield